### ISSUE TITLE
shuffle button raise a javascript error

### ISSUE THREAD

**Issue by fabienmorin** [cozy-labs/cozy-music#118] opened 2016-11-09 11:19 UTC
```
Uncaught TypeError: Cannot read property 'get' of undefined

(anonymous function)	@	playlist.js:103
x.each.x.forEach	@	underscore.js:153
addCurrentPlaylistToUpNext	@	playlist.js:102
m	@	backbone.js:368
y	@	backbone.js:356
d	@	backbone.js:155
c.trigger	@	backbone.js:346
toggleShuffle	@	playerControlsExtended.js:65
dispatch	@	jquery.js:4732
v.handle	@	jquery.js:4544
```
when clicking on the shuffle button

**Comment by flyingrub** [comment] 2016-11-09 12:15
I cannot reproduce this error, what version of music do you use ?

**Comment by fabienmorin** [comment] 2016-11-09 12:53
my cozy instance display Music version 0.5.0
and chromium 53.0.2785.143

You need to enable the debugger to see this problem, else, just nothing happen when I click on it.

**Comment by jsilvestre** [comment] 2016-11-10 11:41
I haven't been able to reproduce the problem neither with the same setup :-/
I also checked the code quickly, and there is no mention of the function `addCurrentPlaylistToUpNext` cc @flyingrub

**Comment by fabienmorin** [comment] 2016-11-10 12:50
I tried again today, without any changes and now it works without any error. I don't know what was wrong.

**Comment by jsilvestre** [comment] 2016-11-10 16:44
It might be a cache issue from a previous version or something like that. Let us know if it comes back! I close the issue for now.

**Closed as completed by jsilvestre** 2016-11-10 16:44 UTC
